### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by eqrion** [WebAssembly/extended-const#5]
Just an FYI. Firefox now supports extended-const as of Firefox Nightly 90.

It's enabled behind an about:config preference `javascript.options.wasm_extended_const`, which defaults to true only in nightly builds. You can also enable this in the SpiderMonkey shell with `--wasm-extended-const`.

**Comment by sbc100** [comment]
Thanks.  I'm updated the overview with the status of the various engines: https://github.com/WebAssembly/extended-const/blob/main/proposals/extended-const/Overview.md#implementation-status
