### ISSUE TITLE
Why do constant expressions have to be so limited?

### ISSUE THREAD

**Issue by 7ombie** [WebAssembly/extended-const#6]
I assume there's a good reason, but I don't know it, and just wanted to ask... Why can't constant expressions use division, bitwise operations etc?

**Comment by sbc100** [comment]
There is proposal I've been pushing to extend const expressions.  If you have instruction you would like to propose, please them there:  https://github.com/WebAssembly/extended-const

**Comment by sbc100** [comment]
If you have instructions you'd like to add to this proposal its not to late at all.

**Comment by sbc100** [comment]
The instruction being proposed so far are the ones the folks have actual use cases for.   Do you have use cases that could benefit from bitwise operations and division?

**Comment by 7ombie** [comment]
@sbc100 - Not really, no, but to be fair, my not having a usecase isn't saying much, as I'm pretty new to WebAssembly.

Speculating a little though, (IIUC) we use constant expressions to initialize globals and to define offsets for active segments. Globals are general purpose variables, so if users (especially WAT programmers) had a larger set of instructions available for initializing globals with, I expect that they would find many uses for them, even if they could also easily think of a work around.

Again, I don't really know enough about WebAssembly to have a strong opinion on things like this. My only aim when questioning these decisions is to understand them better.

**Comment by FlatAssembler** [comment]
> If you have instructions you'd like to add to this proposal its not to late at all.

I think @7ombie asks why one cannot write something like `(i32.const 1+2)` in WebAssembly Text Format and that it gets treated as if it was written `(i32.const 3)`. Or, if we care about making things easy to parse by keeping them LISP-like, why not enable assembly-writers to write something like `(i32.const (+ 1 2))`?

**Comment by sbc100** [comment]
This proposal (this repro) is about enabling more instructions specifically in the constant expressions used in the binary format.   Adding something like `(i32.const (+ 1 2))` to the text format might be a good idea but its not related to this proposal.  Such a proposal would be about improving the text format which this proposal is not doing.

**Comment by 7ombie** [comment]
@sbc100 was right about the context of the question.
