### ISSUE TITLE
Make extended const expressions length-prefixed

### ISSUE THREAD

**Issue by sbc100** [WebAssembly/extended-const#9]
See the discussion here: https://github.com/WebAssembly/design/issues/1443

It seems like this proposal could be good place to inject a new flag to signal the length-prefix on a const expression.

**Comment by sbc100** [comment]
It was decided in the recent CG meeting that we should include the length prefix as part of this proposal, since this is the first time we are going to allow const expressions with more than a single instruction.

Re-opening..

**Comment by sbc100** [comment]
I when investigating whether it was possible to add a flag to signal a "length-prefixed" const expression, I found that it wasn't possible in the all places we currently use const expressions.  

For element and data segment offset we do have segment flags, but for initializing globals we currently do not.   The header for a global currently consists of a type followed by a single byte to signal mutability: https://webassembly.github.io/spec/core/binary/types.html#global-types.   We could possibly add the "extended" flag the mutability bit, but this has at least couple of downsides that I can think of:

1. It would mean that "extended init" flag was specified in a different way for global than for segment offsets.
2. The global type is also used for global imports, where the "extended init" flag would be meaningless/redundant. 

The alternative to finding a place for a new bit/flag would be use a special/reserved instruction to signal that the const expressions is extended, and therefore length prefixed.  For example we could declare that an init expression that begins with `nop` instruction (0x1) is extended, and that the following leb is that length in bytes of the following instruction sequence.   This would make extended const expression two bytes (at least) larger than regular ones.

**Comment by sbc100** [comment]
I took at stab at implementing the `nop` + length prefix approach in wabt: https://github.com/WebAssembly/wabt/pull/2079

**Comment by sbc100** [comment]
After chatting with @dtig I decided it was more explict to go with a new reserved opcode rather than trying to overload `nop`. 

I have now implement WIP patchs for the spec and for wabt:

- https://github.com/WebAssembly/wabt/pull/2079
- https://github.com/WebAssembly/extended-const/pull/13

**Comment by rossberg** [comment]
When we originally designed constant expressions I actually explicitly suggested to add a length prefix to the binary format for future proofness. At that time, the CG concluded that isn't necessary, and that the END marker is good enough. The rationale was that the purpose of length fields elsewhere is the ability to skip and allow parallel decoding or compilation, but that would never be useful for const expressions, because they will never be complex enough to justify such an implementation, even when their format is extended in the future.

What data do we have that suggests that this conclusion is no longer valid?

**Comment by sbc100** [comment]
When we talking about this in last meeting I suggested that being able to decode the wasm "container" format without have to decode the instructions.. and other folks seems to agree it would be useful.   My suggestion was motivated tools llvm's libObject or want's object dump tool that don't always need/want to decode the instructions in a module.

Having said that, the extra code complexity needed to decode these instructions isn't a huge deal for these tools... its not too late to abandon this idea if we think it isn't worth it.

Perhaps we can quickly discuss this at tomorrow meeting, which not doing this now to be a reversal of a decision we made the last meeting.

**Comment by sbc100** [comment]
Here was the discussion from the in person meeting about this: https://github.com/WebAssembly/meetings/blob/48f420242caaba8914f55fd9c4de53de8b90054f/main/2022/CG-10.md?plain=1#L1046-L1064

**Comment by dtig** [comment]
Sorry to have missed the agenda item to today's meeting. I'm wondering if we can continue the discussion on the issue and explicitly loop in the folks as needed. @rossberg given the discussion in the notes, would you prefer we discuss this in an upcoming CG meeting instead?

**Comment by eqrion** [comment]
I was supportive of adding a length-prefix to constant expressions at the CG meeting for the following reasons:

  1. We have a shared implementation limit on the size of function bodies. If we are now going to allow arbitrary sized constant expressions, it seemed good to also support an analogous shared implementation limit for constant expression sizes.
  2. It also conservatively seems useful to be able to allow tools to skip decoding of the initializer of globals if they only care about name/types. Anecdotally, it seems like GC applications may use globals much more heavily than linear memory applications. From the dart barista3 benchmark I have lying around, I see ~9745 globals in the module, each having an expression tree creating potentially very large objects.

I think (1) is a bit weaker as I've realized we could enforce a limit even if the length isn't declared beforehand as even with a length-prefix we still need to check as we go that we've not gone over the prefixed length. So there's no extra implementation complexity with/without the prefix. The only advantage of the prefix is an earlier error.

I think with (2), it's still unlikely we'd do anything parallel with the global section as I wouldn't expect validation to be a bottleneck and any execution of the global initializers will necessarily be ordered as globals can refer to previous globals. I think the primary advantage would be trying to keep the property that decoding can skip past definitions that can be large without having to decode through them.

**Comment by rossberg** [comment]
@dtig, fine by me. However, I will miss the next two dates.

@eqrion, thanks for the background. The tooling argument sounds plausible to me.

On the other hand, one thing to also keep in mind is that this does not just affect globals -- other places use const expressions, too. In particular, element segments can consist of long sequences of individual constant expressions. If we require an extra escape byte + length prefix for every new expression form, then that can easily double the encoding size of element segments that use such forms. That seems like a fairly high cost.

**Comment by eqrion** [comment]
> On the other hand, one thing to also keep in mind is that this does not just affect globals -- other places use const expressions, too. In particular, element segments can consist of long sequences of individual constant expressions. If we require an extra escape byte + length prefix for every new expression form, then that can easily double the encoding size of element segments that use such forms. That seems like a fairly high cost.

Good point. There's no real reason to need to be able to skip over random entries in an elem segment, that's a waste.

Taking a step back, what is useful is a way to skip the entire 'initializer' for either globals or elem segments. Not individual expressions in the case that the initializer is composed of multiple expressions, as with elem segments. So you really do want the byte length to be a part of the global or elem segment encoding, not the `expr` encoding.

And I can't think of a clean way to add that the existing encodings of `elem`/`global`. I really don't want to touch the encoding of `elem` which is already very complex, and `global` would probably require re-using the global type flags as @sbc100 said.

So maybe the answer here is to just have tools blindly scan ahead to find the next `end` instruction whenever they want to skip an expression?

EDIT: thinking about it, there's no easy to skip to the end without decoding as `end` could appear within an immediate.

**Comment by sbc100** [comment]
In today's meeting we discussed this issue and decided not to include this in the current proposal and instead close this issue and advance the proposal as it stands: https://github.com/WebAssembly/meetings/blob/main/main/2023/CG-01-31.md.

There was some concern around the limits this places on parallel compilation of global initializes, but it was suggested that allowing repeated sections would also allow this, since sections already have known lengths.
